language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - 1.8.7

gemfile:
  - src/Gemfile

env:
  - TRAVIS_CI=1

before_script:
  - cd src

branches:
  only:
  - master
